# Calls CI/CD Workflows for Lazaza Test App
name: Test CI/CD

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main

jobs:
  Development-Deploy:
    # Add rules for dependabot PRs
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.base_ref == 'develop')
    uses: ./.github/workflows/test_deploy.yml
    with:
      environment: "development"
    secrets: inherit

  Staging-Deploy:
    if: github.event_name == 'push' && (github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/main')
    needs: [Development-Deploy]
    uses: ./.github/workflows/test_deploy.yml
    with:
      environment: "staging"
    secrets: inherit

  Production-Deploy:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: [Staging-Deploy]
    uses: ./.github/workflows/test_deploy.yml
    with:
      environment: "production"
    secrets: inherit
