name: Run Tests

on:
  push:
    branches:
      - develop  # Adjust as needed

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14  # Adjust as needed

    - name: Install dependencies
      run: npm install

    - name: Run tests with coverage
      run: npm test -- --coverage --watchAll=false

    - name: Generate coverage badge URL
      id: generate_badge_url
      run: |
        COVERAGE_PERCENTAGE=$(npm explore npm run env --global COVERALLS_REPO_TOKEN=none npm exec -- istanbul report --root coverage text-summary | grep -E -o '[0-9]+\.[0-9]+' | head -n 1)
        echo "::set-output name=badge_url::https://img.shields.io/badge/coverage-${COVERAGE_PERCENTAGE}%25-brightgreen.svg"

    - name: Update README with badge
      run: |
        echo "[![Coverage Status](${{ steps.generate_badge_url.outputs.badge_url }})](./coverage/lcov-report/index.html)" > README.md
      if: success()  # Only update README if previous steps are successful


     
